FROM python:3.8

# Install Python dependencies
COPY ./requirements-expansion-service.txt ./requirements.txt
RUN pip install -r requirements.txt

# Copy Python sources
COPY ./jugtoberfest-2022/* ./jugtoberfest-2022/

# Run expansion service
CMD [ "sh", "-c", "python -m apache_beam.runners.portability.expansion_service_main --port=8080 --fully_qualified_name_glob=* --environment_type=DOCKER --environment_config=$IMAGE" ]
