FROM python:3.8

# Install Docker
RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy curl && \
    apt-get install -qy curl && \
    curl -sSL https://get.docker.com/ | sh

# Install Python dependencies
COPY ./requirements-job-service.txt ./requirements.txt
RUN pip install -r requirements.txt


# Run expansion service
CMD [ "sh", "-c", "python -m apache_beam.runners.portability.local_job_service_main --port=8081" ]
